application: skabb-radio
version: 2
runtime: python
api_version: 1



handlers:
- url: /static
  static_dir: static
- url: /js
  static_dir: static
- url: /css
  static_dir: static
- url: /(.*\.(gif|png|jpg|ico|css|js))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))
- url: /oneoff
  script: src/oneoff.py
- url: /feed/.*
  script: src/feed.py
- url: .*
  script: src/main.py

builtins:
  - datastore_admin: on
