application: trumpetapp
version: 1
runtime: python
api_version: 1



handlers:
- url: /static
  static_dir: static
- url: /oneoff
  script: src/oneoff.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /
  static_files: static/index.html
  upload: static/(.*\.(html))
- url: /(.*).xml
  script: src/api.py
- url: /.*
  script: src/dashboard.py
  secure: always


  
builtins:
  - datastore_admin: on
  - remote_api: on