application: skabb-radio
version: 3
runtime: python
api_version: 1



handlers:
- url: /static
  static_dir: static
- url: /javascripts
  static_dir: static
- url: /images
  static_dir: static
- url: /stylesheets
  static_dir: static
- url: /js
  static_dir: static
- url: /css
  static_dir: static
- url: /(.*\.(gif|png|jpg|ico|css|js|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))
- url: /oneoff
  script: src/oneoff.py
- url: /feed/.*
  script: src/feed.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: .*
  script: src/main.py
  
builtins:
  - datastore_admin: on
  - remote_api: on